Ignore wgcf update errors when applying LICENSE_KEY

diff --git a/root/etc/s6-overlay/s6-rc.d/init-prepare/run b/root/etc/s6-overlay/s6-rc.d/init-prepare/run
--- a/root/etc/s6-overlay/s6-rc.d/init-prepare/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-prepare/run
@@ -13,9 +13,9 @@ if [ "${WARP_ENABLED}" = "true" ]; then
   if [ -n "$LICENSE_KEY" ]; then
     echo "*** wgcf: applying license key..."
     sed -i "s/^license_key = .*/license_key = '${LICENSE_KEY}'/" /config/wgcf-account.toml
-    # Update account with the new license key
+    # Update account with the new license key (ignore errors if API incompatible)
     echo "*** wgcf: updating account with license key..."
-    wgcf update --config /config/wgcf-account.toml
+    wgcf update --config /config/wgcf-account.toml || echo "*** wgcf: update failed, will regenerate profile..."
     # Force regeneration of profile configs
     rm -f /config/wgcf-profile.conf
     rm -f /config/wireproxy.conf
